"""description of what changed

Revision ID: 29a4c7d64fe3
Revises: 
Create Date: 2026-03-04 11:38:41.461989

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '29a4c7d64fe3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_listings', sa.Column('experience_level', sa.String(length=32), nullable=False))
    op.add_column('job_listings', sa.Column('skills', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False))
    op.create_index('ix_job_listings_experience_level', 'job_listings', ['experience_level'], unique=False)
    op.create_index('ix_job_listings_org_exp', 'job_listings', ['org_id', 'experience_level'], unique=False)
    op.create_index('ix_job_listings_org_id', 'job_listings', ['org_id'], unique=False)
    op.create_index('ix_job_listings_org_status', 'job_listings', ['org_id', 'status'], unique=False)
    op.create_index('ix_job_listings_status', 'job_listings', ['status'], unique=False)
    op.add_column('orgs', sa.Column('created_by', sa.UUID(), nullable=False))
    op.add_column('orgs', sa.Column('status', sa.String(length=32), nullable=False))
    op.add_column('orgs', sa.Column('contact', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False))
    op.add_column('orgs', sa.Column('billing', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False))
    op.add_column('orgs', sa.Column('logo_url', sa.String(length=512), nullable=True))
    op.add_column('orgs', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('orgs', sa.Column('industry', sa.String(length=100), nullable=True))
    op.add_column('orgs', sa.Column('headcount', sa.String(length=16), nullable=True))
    op.alter_column('orgs', 'slug',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=150),
               existing_nullable=False)
    op.create_index('ix_orgs_created_by', 'orgs', ['created_by'], unique=False)
    op.create_index('ix_orgs_slug', 'orgs', ['slug'], unique=True)
    op.create_index('ix_orgs_status', 'orgs', ['status'], unique=False)
    op.create_foreign_key(None, 'orgs', 'users', ['created_by'], ['id'], ondelete='RESTRICT')
    op.add_column('transcripts', sa.Column('transcript_text', sa.Text(), nullable=False))
    op.drop_column('transcripts', 'Transcript_text')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transcripts', sa.Column('Transcript_text', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('transcripts', 'transcript_text')
    op.drop_constraint(None, 'orgs', type_='foreignkey')
    op.drop_index('ix_orgs_status', table_name='orgs')
    op.drop_index('ix_orgs_slug', table_name='orgs')
    op.drop_index('ix_orgs_created_by', table_name='orgs')
    op.alter_column('orgs', 'slug',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.drop_column('orgs', 'headcount')
    op.drop_column('orgs', 'industry')
    op.drop_column('orgs', 'description')
    op.drop_column('orgs', 'logo_url')
    op.drop_column('orgs', 'billing')
    op.drop_column('orgs', 'contact')
    op.drop_column('orgs', 'status')
    op.drop_column('orgs', 'created_by')
    op.drop_index('ix_job_listings_status', table_name='job_listings')
    op.drop_index('ix_job_listings_org_status', table_name='job_listings')
    op.drop_index('ix_job_listings_org_id', table_name='job_listings')
    op.drop_index('ix_job_listings_org_exp', table_name='job_listings')
    op.drop_index('ix_job_listings_experience_level', table_name='job_listings')
    op.drop_column('job_listings', 'skills')
    op.drop_column('job_listings', 'experience_level')
    # ### end Alembic commands ###
